;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


HoneyHeist_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; New song

@instruments:
	.word @env1,@env0,@env8,@env9
	.word @env2,@env5,@env0,@env0
	.word @env3,@env6,@env0,@env0
	.word @env4,@env7,@env0,@env0

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c6,$cf,$cf,$cd,$c9,$c5,$c3,$c1,$c0,$00,$08
@env2:
	.byte $c6,$c5,$02,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$0b
@env3:
	.byte $ce,$cb,$c6,$c2,$c0,$00,$04
@env4:
	.byte $c0,$cf,$05,$ce,$ce,$cb,$ca,$c9,$c8,$c7,$c7,$c6,$c5,$c4,$c3,$c2
	.byte $c1,$c0,$00,$11
@env5:
	.byte $c0,$c1,$00,$01
@env6:
	.byte $c0,$c4,$00,$01
@env7:
	.byte $bc,$c2,$ba,$be,$c0,$00,$04
@env8:
	.byte $c0,$c0,$bf,$be,$bf,$c0,$00,$00
@env9:
	.byte $c0,$c2,$00,$01


; New song
@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $bf
@ref1:
	.byte $bf
@ref2:
	.byte $bf
@ref3:
	.byte $bf
@ref4:
	.byte $bf
@ref5:
	.byte $bf
	.byte $fd
	.word @song0ch0loop

; New song
@song0ch1:
@song0ch1loop:
@ref6:
	.byte $bf
@ref7:
	.byte $bf
@ref8:
	.byte $bf
@ref9:
	.byte $80,$28,$81,$2f,$81,$2d,$81,$2c,$81,$2a,$81,$28,$85,$2d,$81,$2f
	.byte $85,$2d,$81,$2f,$81,$31,$81,$2c,$2d,$81,$2c,$2a,$81
@ref10:
	.byte $28,$81,$2f,$81,$2d,$81,$2c,$81,$2a,$81,$28,$85,$2d,$81,$2f,$85
	.byte $2d,$81,$2f,$81,$31,$81,$2c,$2d,$81,$2c,$2a,$81
	.byte $ff,$1c
	.word @ref10
	.byte $fd
	.word @song0ch1loop

; New song
@song0ch2:
@song0ch2loop:
@ref12:
	.byte $80,$34,$8d,$36,$81,$34,$89,$33,$8d,$31,$8d
@ref13:
	.byte $34,$8d,$36,$81,$34,$89,$33,$8d,$31,$8d
	.byte $ff,$0a
	.word @ref13
	.byte $ff,$0a
	.word @ref13
	.byte $ff,$0a
	.word @ref13
	.byte $ff,$0a
	.word @ref13
	.byte $fd
	.word @song0ch2loop

; New song
@song0ch3:
@song0ch3loop:
@ref18:
	.byte $84,$0c,$85,$82,$08,$85,$84,$0c,$85,$82,$08,$85,$84,$0c,$85,$82
	.byte $08,$85,$84,$0c,$85,$82,$08,$85
	.byte $ff,$10
	.word @ref18
@ref20:
	.byte $86,$10,$89,$10,$81,$10,$89,$10,$81,$10,$89,$10,$81,$10,$81,$05
	.byte $05,$05,$81,$0e,$81
	.byte $ff,$10
	.word @ref18
	.byte $ff,$10
	.word @ref18
	.byte $ff,$14
	.word @ref20
	.byte $fd
	.word @song0ch3loop

; New song
@song0ch4:
@song0ch4loop:
@ref24:
	.byte $bf
@ref25:
	.byte $bf
@ref26:
	.byte $bf
@ref27:
	.byte $bf
@ref28:
	.byte $bf
@ref29:
	.byte $bf
	.byte $fd
	.word @song0ch4loop
